# Generated by Django 5.1.3 on 2024-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cveGrupo', models.CharField(max_length=10, unique=True)),
                ('nombreGrupo', models.CharField(max_length=20)),
                ('cuatrimestreGrupo', models.CharField(max_length=30)),
                ('aulaNombre', models.CharField(max_length=30)),
                ('aulaUbicacion', models.CharField(max_length=100)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
