# Generated by Django 5.1.3 on 2024-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cveCarrera', models.CharField(max_length=10, unique=True)),
                ('nombreCarrera', models.CharField(max_length=255)),
                ('areaCarrera', models.CharField(max_length=30)),
                ('planEstudios', models.CharField(max_length=30)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
